list_files = \
[
	"main.cpp",
	"util.cpp",
	"shaders.cpp",
	"shaders/compile_shader.cpp"
]

list_shaders = \
[
	"normal_map_shader",
]

libs = \
[
	"GL",
	"GLEW",
	"SDL2",
]

libpath = \
[
	"/usr/lib",
	"/usr/local/lib"
]

for shad in list_shaders:
	path = "shaders/" + shad + "/" + shad + ".cpp"
	list_files.append(path)

env = Environment();
env.Append(CCFLAGS = '-std=c++11')

debug = ARGUMENTS.get("debug", 0);
if debug == 'true':
	env.Append(CCFLAGS = '-g')

env.Program \
( \
	"main",
	list_files,
	LIBS = libs,
	LIBPATH = libpath,
	CPPPATH = "."
)
